version: '3'

services:
  estimate-be:
    build: .
    ports:
      - "5001:5001"  # WebSocket server port
      - "5003:5003"  # HTTP server port
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: estimate-kafka:9092
    depends_on:
      - estimate-kafka
      - estimate-redis
    networks:
      - estimate-network

  estimate-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    depends_on:
      - estimate-kafka
    networks:
      - estimate-network

  estimate-kafka:
    image: 'bitnami/kafka:3.7.1'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@estimate-kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    ports:
      - "9092:9092"
    networks:
      - estimate-network

networks:
  estimate-network:
    driver: bridge