version: '3'

services:
  estimate-be:
    # image: .
    build: .
    ports:
      - '5001:5001'  
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - estimate-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - estimate-network

networks:
  estimate-network: